services:
  post-db:
    container_name: postprovider-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGSSLMODE: ${DB_SSL}
      TZ: ${DB_TIMEZONE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - post-service
  post-db-migrations:
    container_name: postprovider-db-migrations
    build: ./migrations
    depends_on:
      - post-db
    networks:
      - post-service
  post-service:
    container_name: postprovider-service
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - post-db
    networks:
      - post-service
networks:
  post-service:
volumes:
  pgdata: {}
