// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "post-storage-service/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPostRepository is a mock of PostRepository interface.
type MockPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostRepositoryMockRecorder
	totalElementsCount int
}

// MockPostRepositoryMockRecorder is the mock recorder for MockPostRepository.
type MockPostRepositoryMockRecorder struct {
	mock *MockPostRepository
}

// NewMockPostRepository creates a new mock instance.
func NewMockPostRepository(ctrl *gomock.Controller) *MockPostRepository {
	mock := &MockPostRepository{ctrl: ctrl}
	mock.recorder = &MockPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostRepository) EXPECT() *MockPostRepositoryMockRecorder {
	return m.recorder
}

// SavePosts mocks base method.
func (m *MockPostRepository) SavePosts(ctx context.Context, posts []model.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePosts", ctx, posts)
	ret0, _ := ret[0].(error)

	m.totalElementsCount += len(posts)

	return ret0
}

// SavePosts indicates an expected call of SavePosts.
func (mr *MockPostRepositoryMockRecorder) SavePosts(ctx, posts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePosts", reflect.TypeOf((*MockPostRepository)(nil).SavePosts), ctx, posts)
}

func (mr *MockPostRepository) GetTotalPostCount() int {
	return mr.totalElementsCount
}
